
myListOfHistograms   =[
    "presel_M3"                                  ,
    "phosel_Nphotons"                            ,
    "phosel_Nphotons_GenuinePhoton"              ,
    "phosel_Nphotons_MisIDEle"                   ,
    "phosel_Nphotons_HadronicPhoton"             ,
    "phosel_Nphotons_HadronicFake"               ,
    "phosel_LeadingPhotonEt"                     ,
    "phosel_LeadingPhotonEt_GenuinePhoton"       ,
    "phosel_LeadingPhotonEt_MisIDEle"            ,
    "phosel_LeadingPhotonEt_HadronicPhoton"      ,
    "phosel_LeadingPhotonEt_HadronicFake"        ,
    "phosel_LeadingPhotonEta_HadronicFake"       ,
    "phosel_M3"                                  ,
    "phosel_M3_GenuinePhoton"                    ,
    "phosel_M3_MisIDEle"                         ,
    "phosel_M3_HadronicPhoton"                   ,
    "phosel_M3_HadronicFake"                     ,
    "phosel_mediumID_ChIso"                      ,
    "phosel_mediumID_ChIso_GenuinePhoton"        ,
    "phosel_mediumID_ChIso_MisIDEle"             ,
    "phosel_mediumID_ChIso_HadronicPhoton"       ,
    "phosel_mediumID_ChIso_HadronicFake"         ,
    "phosel_AntiSIEIE_ChIso"                     ,
    "phosel_AntiSIEIE_ChIso_GenuinePhoton"       ,
    "phosel_AntiSIEIE_ChIso_MisIDEle"            ,
    "phosel_AntiSIEIE_ChIso_HadronicPhoton"      ,
    "phosel_AntiSIEIE_ChIso_HadronicFake"        ,
    "phosel_noCut_SIEIE_noChIso"                 ,
    "phosel_noCut_SIEIE_noChIso_GenuinePhoton"   ,
    "phosel_noCut_SIEIE_noChIso_MisIDEle"        ,
    "phosel_noCut_SIEIE_noChIso_HadronicPhoton"  ,
    "phosel_noCut_SIEIE_noChIso_HadronicFake"    ,
    "phosel_noCut_SIEIE"                         ,
    "phosel_noCut_SIEIE_GenuinePhoton"           ,
    "phosel_noCut_SIEIE_MisIDEle"                ,
    "phosel_noCut_SIEIE_HadronicPhoton"          ,
    "phosel_noCut_SIEIE_HadronicFake"            ,
    "phosel_PhotonCategory"                      ,
    "phosel_MassEGamma"                          ,
    "phosel_MassEGamma_GenuinePhoton"            ,
    "phosel_MassEGamma_MisIDEle"                 ,
    "phosel_MassEGamma_HadronicPhoton"           ,
    "phosel_MassEGamma_HadronicFake"             ,
    "presel_elePt"                               ,
    "presel_muEta"                               ,
    "phosel_elePt"                               ,
    "phosel_elePt_GenuinePhoton"                 ,
    "phosel_elePt_MisIDEle"                      ,
    "phosel_elePt_HadronicPhoton"                ,
    "phosel_elePt_HadronicFake"                  ,
    "phosel_muPt"                                ,
    "phosel_muPt_GenuinePhoton"                  ,
    "phosel_muPt_MisIDEle"                       ,
    "phosel_muPt_HadronicPhoton"                 ,
    "phosel_muPt_HadronicFake"                   ,
    "phosel_Njet"                                ,
    "phosel_Njet_GenuinePhoton"                  ,
    "phosel_Njet_MisIDEle"                       ,
    "phosel_Njet_HadronicPhoton"                 ,
    "phosel_Njet_HadronicFake"                   ,
]
    
    
    
    
    
    
    
    
    
    



# myListOfHistograms   =[
#     "presel_jet1Pt"                              ,
#     "presel_Njet"                                ,
#     "presel_Nbjet"                               ,
#     "presel_muPt"                                ,
#     "presel_elePt"                               ,
#     "presel_muEta"                               ,
#     "presel_muPhi"                               ,
#     "presel_eleSCEta"                            ,
#     "presel_elePhi"                              ,
#     "presel_M3"                                  ,
#     "presel_MET"                                 ,
#     "presel_METPhi"                              ,
#     "presel_nVtx"                                ,
#     "presel_WtransMass"                          ,
#     "phosel_nVtx"                                ,
#     "phosel_nVtx_GenuinePhoton"                  ,
#     "phosel_nVtx_MisIDEle"                       ,
#     "phosel_nVtx_HadronicPhoton"                 ,
#     "phosel_nVtx_HadronicFake"                   ,
#     "phosel_jet1Pt"                              ,
#     "phosel_jet1Pt_GenuinePhoton"                ,
#     "phosel_jet1Pt_MisIDEle"                     ,
#     "phosel_jet1Pt_HadronicPhoton"               ,
#     "phosel_jet1Pt_HadronicFake"                 ,
#     "phosel_Nphotons"                            ,
#     "phosel_Nphotons_GenuinePhoton"              ,
#     "phosel_Nphotons_MisIDEle"                   ,
#     "phosel_Nphotons_HadronicPhoton"             ,
#     "phosel_Nphotons_HadronicFake"               ,
#     "phosel_LeadingPhotonEt"                     ,
#     "phosel_LeadingPhotonEt_GenuinePhoton"       ,
#     "phosel_LeadingPhotonEt_MisIDEle"            ,
#     "phosel_LeadingPhotonEt_HadronicPhoton"      ,
#     "phosel_LeadingPhotonEt_HadronicFake"        ,
#     "phosel_LeadingPhotonPhi"                    ,
#     "phosel_LeadingPhotonPhi_GenuinePhoton"      ,
#     "phosel_LeadingPhotonPhi_MisIDEle"           ,
#     "phosel_LeadingPhotonPhi_HadronicPhoton"     ,
#     "phosel_LeadingPhotonPhi_HadronicFake"       ,
#     "phosel_LeadingPhotonEta"                    ,
#     "phosel_LeadingPhotonEta_GenuinePhoton"      ,
#     "phosel_LeadingPhotonEta_MisIDEle"           ,
#     "phosel_LeadingPhotonEta_HadronicPhoton"     ,
#     "phosel_LeadingPhotonEta_HadronicFake"       ,
#     "phosel_WtransMass"                          ,
#     "phosel_WtransMass_GenuinePhoton"            ,
#     "phosel_WtransMass_MisIDEle"                 ,
#     "phosel_WtransMass_HadronicPhoton"           ,
#     "phosel_WtransMass_HadronicFake"             ,
#     "phosel_M3"                                  ,
#     "phosel_M3_GenuinePhoton"                    ,
#     "phosel_M3_MisIDEle"                         ,
#     "phosel_M3_HadronicPhoton"                   ,
#     "phosel_M3_HadronicFake"                     ,
#     "phosel_MET"                                 ,
#     "phosel_MET_GenuinePhoton"                   ,
#     "phosel_MET_MisIDEle"                        ,
#     "phosel_MET_HadronicPhoton"                  ,
#     "phosel_MET_HadronicFake"                    ,
#     "phosel_elePt"                               ,
#     "phosel_elePt_GenuinePhoton"                 ,
#     "phosel_elePt_MisIDEle"                      ,
#     "phosel_elePt_HadronicPhoton"                ,
#     "phosel_elePt_HadronicFake"                  ,
#     "phosel_eleSCEta"                            ,
#     "phosel_eleSCEta_GenuinePhoton"              ,
#     "phosel_eleSCEta_MisIDEle"                   ,
#     "phosel_eleSCEta_HadronicPhoton"             ,
#     "phosel_eleSCEta_HadronicFake"               ,
#     "phosel_muPt"                                ,
#     "phosel_muPt_GenuinePhoton"                  ,
#     "phosel_muPt_MisIDEle"                       ,
#     "phosel_muPt_HadronicPhoton"                 ,
#     "phosel_muPt_HadronicFake"                   ,
#     "phosel_muEta"                               ,
#     "phosel_muEta_GenuinePhoton"                 ,
#     "phosel_muEta_MisIDEle"                      ,
#     "phosel_muEta_HadronicPhoton"                 ,
#     "phosel_muEta_HadronicFake"                   ,
#     "phosel_Njet"                                ,
#     "phosel_Njet_GenuinePhoton"                  ,
#     "phosel_Njet_MisIDEle"                       ,
#     "phosel_Njet_HadronicPhoton"                 ,
#     "phosel_Njet_HadronicFake"                   ,
#     "phosel_Nbjet"                               ,
#     "phosel_Nbjet_GenuinePhoton"                 ,
#     "phosel_Nbjet_MisIDEle"                      ,
#     "phosel_Nbjet_HadronicPhoton"                ,
#     "phosel_Nbjet_HadronicFake"                  ,
#     "phosel_SIEIE"                               ,
#     "phosel_SIEIE_GenuinePhoton"                 ,
#     "phosel_SIEIE_MisIDEle"                      ,
#     "phosel_SIEIE_HadronicPhoton"                 ,
#     "phosel_SIEIE_HadronicFake"                   ,
#     "phosel_noCut_SIEIE_noChIso"                 ,
#     "phosel_noCut_SIEIE_noChIso_GenuinePhoton"   ,
#     "phosel_noCut_SIEIE_noChIso_MisIDEle"        ,
#     "phosel_noCut_SIEIE_noChIso_HadronicPhoton"  ,
#     "phosel_noCut_SIEIE_noChIso_HadronicFake"    ,
#     "phosel_noCut_SIEIE"                         ,
#     "phosel_noCut_SIEIE_GenuinePhoton"           ,
#     "phosel_noCut_SIEIE_MisIDEle"                ,
#     "phosel_noCut_SIEIE_HadronicPhoton"          ,
#     "phosel_noCut_SIEIE_HadronicFake"            ,
#     "phosel_mediumID_ChIso"                      ,
#     "phosel_mediumID_ChIso_GenuinePhoton"        ,
#     "phosel_mediumID_ChIso_MisIDEle"             ,
#     "phosel_mediumID_ChIso_HadronicPhoton"       ,
#     "phosel_mediumID_ChIso_HadronicFake"         ,
#     "phosel_noCut_ChIso"                         ,
#     "phosel_noCut_ChIso_GenuinePhoton"           ,
#     "phosel_noCut_ChIso_MisIDEle"                ,
#     "phosel_noCut_ChIso_HadronicPhoton"          ,
#     "phosel_noCut_ChIso_HadronicFake"            ,
#     "phosel_AntiSIEIE_ChIso"                     ,
#     "phosel_AntiSIEIE_ChIso_GenuinePhoton"       ,
#     "phosel_AntiSIEIE_ChIso_MisIDEle"            ,
#     "phosel_AntiSIEIE_ChIso_HadronicPhoton"      ,
#     "phosel_AntiSIEIE_ChIso_HadronicFake"        ,
#     "phosel_NGenuinePhoton"                      ,
#     "phosel_NMisIDEle"                           ,
#     "phosel_NHadronicPhoton"                     ,
#     "phosel_NHadronicFake"                       ,
#     "phosel_PhotonCategory"                      ,
#     "phosel_MassEGamma"                          ,
#     "phosel_MassEGamma_GenuinePhoton"            ,
#     "phosel_MassEGamma_MisIDEle"                 ,
#     "phosel_MassEGamma_HadronicPhoton"           ,
#     "phosel_MassEGamma_HadronicFake"             ,
#     "phosel_noCutSIEIEChIso_GenuinePhoton"       ,
#     "phosel_noCutSIEIEChIso_MisIDEle"            ,
#     "phosel_noCutSIEIEChIso_HadronicPhoton"      ,
#     "phosel_noCutSIEIEChIso_HadronicFake"        ,
#     "phosel_noCutSIEIEChIso"                     
# ]



# myListOfHistograms   =[
#     "presel_jet1Pt"                              ,
#     "presel_Njet"                                ,
#     "presel_Nbjet"                               ,
#     "presel_muPt"                                ,
#     "presel_muEta"                               ,
#     "presel_muPhi"                               ,
#     "presel_elePt"                               ,
#     "presel_eleSCEta"                            ,
#     "presel_elePhi"                              ,
#     "presel_M3"                                  ,
#     "presel_nVtx"                                ,
#     "phosel_nVtx"                                ,
#     "phosel_nVtx_GenuinePhoton"                  ,
#     "phosel_nVtx_MisIDEle"                       ,
#     "phosel_nVtx_HadronicPhoton"                 ,
#     "phosel_nVtx_HadronicFake"                   ,
#     "phosel_jet1Pt"                              ,
#     "phosel_jet1Pt_GenuinePhoton"                ,
#     "phosel_jet1Pt_MisIDEle"                     ,
#     "phosel_jet1Pt_HadronicPhoton"               ,
#     "phosel_jet1Pt_HadronicFake"                 ,
#     "phosel_Nphotons"                            ,
#     "phosel_Nphotons_GenuinePhoton"              ,
#     "phosel_Nphotons_MisIDEle"                   ,
#     "phosel_Nphotons_HadronicPhoton"             ,
#     "phosel_Nphotons_HadronicFake"               ,
#     "phosel_LeadingPhotonEt"                     ,
#     "phosel_LeadingPhotonEt_GenuinePhoton"       ,
#     "phosel_LeadingPhotonEt_MisIDEle"            ,
#     "phosel_LeadingPhotonEt_HadronicPhoton"      ,
#     "phosel_LeadingPhotonEt_HadronicFake"        ,
#     "phosel_LeadingPhotonPhi"                    ,
#     "phosel_LeadingPhotonPhi_GenuinePhoton"      ,
#     "phosel_LeadingPhotonPhi_MisIDEle"           ,
#     "phosel_LeadingPhotonPhi_HadronicPhoton"     ,
#     "phosel_LeadingPhotonPhi_HadronicFake"       ,
#     "phosel_LeadingPhotonEta"                    ,
#     "phosel_LeadingPhotonEta_GenuinePhoton"      ,
#     "phosel_LeadingPhotonEta_MisIDEle"           ,
#     "phosel_LeadingPhotonEta_HadronicPhoton"     ,
#     "phosel_LeadingPhotonEta_HadronicFake"       ,
#     "phosel_elePt"                               ,
#     "phosel_elePt_GenuinePhoton"                 ,
#     "phosel_elePt_MisIDEle"                      ,
#     "phosel_elePt_HadronicPhoton"                ,
#     "phosel_elePt_HadronicFake"                  ,
#     "phosel_eleSCEta"                            ,
#     "phosel_eleSCEta_GenuinePhoton"              ,
#     "phosel_eleSCEta_MisIDEle"                   ,
#     "phosel_eleSCEta_HadronicPhoton"             ,
#     "phosel_eleSCEta_HadronicFake"               ,
#     "phosel_muPt"                                ,
#     "phosel_muPt_GenuinePhoton"                  ,
#     "phosel_muPt_MisIDEle"                       ,
#     "phosel_muPt_HadronicPhoton"                 ,
#     "phosel_muPt_HadronicFake"                   ,
#     "phosel_muEta"                               ,
#     "phosel_muEta_GenuinePhoton"                 ,
#     "phosel_muEta_MisIDEle"                      ,
#     "phosel_muEta_HadronicPhoton"                 ,
#     "phosel_muEta_HadronicFake"                   ,
#     "phosel_Njet"                                ,
#     "phosel_Njet_GenuinePhoton"                  ,
#     "phosel_Njet_MisIDEle"                       ,
#     "phosel_Njet_HadronicPhoton"                 ,
#     "phosel_Njet_HadronicFake"                   ,
#     "phosel_Nbjet"                               ,
#     "phosel_Nbjet_GenuinePhoton"                 ,
#     "phosel_Nbjet_MisIDEle"                      ,
#     "phosel_Nbjet_HadronicPhoton"                ,
#     "phosel_Nbjet_HadronicFake"                  ,
#     "phosel_NGenuinePhoton"                      ,
#     "phosel_NMisIDEle"                           ,
#     "phosel_NHadronicPhoton"                     ,
#     "phosel_NHadronicFake"                       ,
#     "phosel_PhotonCategory"                      ,
# ]














