
myPlotList  = [
    "presel_jet1Pt"                              ,
    #"presel_fwdjet1Pt"                           ,
    # "presel_jet2Pt"                              ,
    # "presel_jet3Pt"                              ,
    # "presel_jet4Pt"                              ,
    "presel_Njet"                                ,
    # "presel_NFwdjet"                             ,
    "presel_Nbjet"                               ,
    "presel_muPt"                                ,
    "presel_muEta"                               ,
    "presel_muPhi"                               ,
    "presel_elePt"                               ,
    "presel_eleSCEta"                            ,
    "presel_elePhi"                              ,
    "presel_M3"                                  ,
    "presel_MET"                                 ,
    "presel_METPhi"                              , 
    "presel_nVtx"                                ,
    "presel_WtransMass"                          ,
    # "presel_WtransMass_METless30"                ,
    # "presel_WtransMass_METgreat30"               ,
    # "presel_WtransMass_METless30_control"        ,
    # "presel_WtransMass_METgreat30_control"       ,
    # "phosel_WtransMass_METless30"                ,
    # "phosel_WtransMass_METgreat30"               ,
    "presel_HT"                                  ,
    #"phosel_nVtx"                                , # right now it is not splited into pho category
    # "presel_nVtxup"                              ,
    # "presel_nVtxdo"                              ,
    # "presel_nVtxNoPU"                            ,
    "phosel_jet1Pt"                              ,
    # "phosel_jet1Pt_GenuinePhoton"                ,
    # "phosel_jet1Pt_MisIDEle"                     ,
    # "phosel_jet1Pt_HadronicPhoton"               ,
    # "phosel_jet1Pt_HadronicFake"                 ,
    # "phosel_fwdjet1Pt"                           ,
    # "phosel_NFwdjet"                             ,
    #"phosel_Nphotons"                            , 
    # "phosel_Nphotons_GenuinePhoton"              ,
    # "phosel_Nphotons_MisIDEle"                   ,
    # "phosel_Nphotons_NonPrompt"                  ,
    "phosel_LeadingPhotonEt"                     ,
    # "phosel_LeadingPhotonEt_GenuinePhoton"       ,
    # "phosel_LeadingPhotonEt_MisIDEle"            ,
    # "phosel_LeadingPhotonEt_HadronicPhoton"      ,
    # "phosel_LeadingPhotonEt_HadronicFake"        ,
    # "phosel_LeadingPhotonPhi"                    ,
    # "phosel_LeadingPhotonPhi_GenuinePhoton"      ,
    # "phosel_LeadingPhotonPhi_MisIDEle"           ,
    # "phosel_LeadingPhotonPhi_HadronicPhoton"     ,
    # "phosel_LeadingPhotonPhi_HadronicFake"       ,
    "phosel_LeadingPhotonEta"                    ,
    # "phosel_LeadingPhotonEta_GenuinePhoton"      ,
    # "phosel_LeadingPhotonEta_MisIDEle"           ,
    # "phosel_LeadingPhotonEta_HadronicPhoton"     ,
    # "phosel_LeadingPhotonEta_HadronicFake"       ,
    # "phosel_LeadingPhotonEt_Isolated"            ,
    # "phosel_LeadingPhotonEt_NonPrompt"           ,
    # "phosel_dRLeadingPhotonJet"                  ,
    # "phosel_dRLeadingPhotonJet_GenuinePhoton"    ,
    # "phosel_dRLeadingPhotonJet_MisIDEle"         ,
    # "phosel_dRLeadingPhotonJet_NonPrompt"        ,
    # "phosel_dRLeadingPromptPhotonJet"            ,
    # "phosel_dRLeadingPromptPhotonLepton"         ,
    # "phosel_dRLeadingHadronicPhotonLepton"       ,
    # "phosel_dRLeadingPhotonLepton_GenuinePhoton" ,
    # "phosel_dRLeadingPhotonLepton_MisIDEle"      ,
    # "phosel_dRLeadingPhotonLepton_NonPrompt"     ,
    # "phosel_dRLeadingHadronicFakeLepton"         ,
    # "phosel_dRLeadingPhotonLepton"               ,
    "phosel_WtransMass"                          ,
    # "phosel_WtransMass_GenuinePhoton"            ,
    # "phosel_WtransMass_MisIDEle"                 ,
    # "phosel_WtransMass_HadronicPhoton"           ,
    # "phosel_WtransMass_HadronicFake"             ,
    # "phosel_HT"                                  , # I don't have pho category yet
    # "phosel_HT_GenuinePhoton"                    ,
    # "phosel_HT_MisIDEle"                         ,
    # "phosel_HT_NonPrompt"                        ,
    "phosel_M3"                                  ,
    # "phosel_M3_GenuinePhoton"                    ,
    # "phosel_M3_MisIDEle"                         ,
    # "phosel_M3_HadronicPhoton"                   ,
    # "phosel_M3_HadronicFake"                     ,
    # "phosel_M3_NonPrompt"                        ,
    # "phosel_M3_gamma"                            ,
    #"phosel_MET"                                 , # I don't have pho category yet
    #"phosel_elePt"                               ,
    # "phosel_elePt_GenuinePhoton"                 ,
    # "phosel_elePt_MisIDEle"                      ,
    # "phosel_elePt_NonPrompt"                     ,
    #"phosel_eleSCEta"                            ,  # I don't have pho category yet
    # "phosel_eleSCEta_GenuinePhoton"              ,
    # "phosel_eleSCEta_MisIDEle"                   ,
    # "phosel_eleSCEta_NonPrompt"                  ,
    #"phosel_muPt"                                ,  # I don't have pho category yet
    # "phosel_muPt_GenuinePhoton"                  ,
    # "phosel_muPt_MisIDEle"                       ,
    # "phosel_muPt_NonPrompt"                      ,
    #"phosel_muEta"                               ,  # I don't have pho category yet
    # "phosel_muEta_GenuinePhoton"                 ,
    # "phosel_muEta_MisIDEle"                      ,
    # "phosel_muEta_NonPrompt"                     ,
    #"phosel_Njet"                                ,  # I don't have pho category yet
    # "phosel_Njet_GenuinePhoton"                  ,
    # "phosel_Njet_MisIDEle"                       ,
    # "phosel_Njet_HadronicPhoton"                 ,
    # "phosel_Njet_HadronicFake"                   ,
    # "phosel_Njet_NonPrompt"                      ,
    # "phosel_NfwdJet"                             ,
    #"phosel_Nbjet"                               ,  # I don't have pho category yet
    # "phosel_HoverE"                              ,
    # "phosel_noCut_HoverE"                        ,
    #"phosel_SIEIE"                               ,  # I don't have pho category yet
    # "phosel_SIEIE_GenuinePhoton"                 ,
    # "phosel_SIEIE_MisIDEle"                      ,
    # "phosel_SIEIE_NonPrompt"                     ,
    #"phosel_ChIso"                               ,  # I don't have pho category yet
    # "phosel_ChIso_GenuinePhoton"                 ,
    # "phosel_ChIso_MisIDEle"                      ,
    # "phosel_ChIso_NonPrompt"                     ,
    "phosel_noCut_SIEIE_noChIso"                 ,
    # "phosel_noCut_SIEIE_noChIso_GenuinePhoton"   ,
    # "phosel_noCut_SIEIE_noChIso_MisIDEle"        ,
    # "phosel_noCut_SIEIE_noChIso_HadronicPhoton"  ,
    # "phosel_noCut_SIEIE_noChIso_HadronicFake"    ,
    # "phosel_noCut_SIEIE_noChIso_NonPrompt"       ,
    
    "phosel_noCut_SIEIE"                         ,
    # "phosel_noCut_SIEIE_GenuinePhoton"           ,
    # "phosel_noCut_SIEIE_MisIDEle"                ,
    # "phosel_noCut_SIEIE_HadronicPhoton"          ,
    # "phosel_noCut_SIEIE_HadronicFake"            ,
    # "phosel_noCut_SIEIE_NonPrompt"               ,
    "phosel_mediumID_ChIso"                      ,
    # "phosel_mediumID_ChIso_GenuinePhoton"        ,
    # "phosel_mediumID_ChIso_MisIDEle"             ,
    # "phosel_mediumID_ChIso_HadronicPhoton"       ,
    # "phosel_mediumID_ChIso_HadronicFake"         ,
    #"phosel_noCut_ChIso"                         , # this is same as phosel_mediumID_ChIso
    # "phosel_noCut_ChIso_PUdown"                  ,
    # "phosel_noCut_ChIso_PUup"                    ,
    # "phosel_noCut_ChIso_0nVtx15"                 ,
    # "phosel_noCut_ChIso_15nVtx20"                ,
    # "phosel_noCut_ChIso_20nVtx25"                ,
    # "phosel_noCut_ChIso_25nVtx50"                ,
    # "phosel_noCut_ChIso_Nonprompt_PUdown"        ,
    # "phosel_noCut_ChIso_Nonprompt_PUup"          ,
    # "phosel_noCut_ChIso_GenuinePhoton"           ,
    # "phosel_noCut_ChIso_MisIDEle"                ,
    # "phosel_noCut_ChIso_HadronicPhoton"          ,
    # "phosel_noCut_ChIso_HadronicFake"            ,
    #"phosel_AntiSIEIE_ChIso"                     ,
    # "phosel_AntiSIEIE_ChIso_GenuinePhoton"       ,
    # "phosel_AntiSIEIE_ChIso_MisIDEle"            ,
    # "phosel_AntiSIEIE_ChIso_HadronicPhoton"      ,
    # "phosel_AntiSIEIE_ChIso_HadronicFake"        ,
    # "phosel_AntiSIEIE_SB1_ChIso"                 ,
    # "phosel_AntiSIEIE_SB1_ChIso_GenuinePhoton"   ,
    # "phosel_AntiSIEIE_SB1_ChIso_MisIDEle"        ,
    # "phosel_AntiSIEIE_SB1_ChIso_HadronicPhoton"  ,
    # "phosel_AntiSIEIE_SB1_ChIso_HadronicFake"    ,
    # "phosel_AntiSIEIE_SB2_ChIso"                 ,
    # "phosel_AntiSIEIE_SB2_ChIso_GenuinePhoton"   ,
    # "phosel_AntiSIEIE_SB2_ChIso_MisIDEle"        ,
    # "phosel_AntiSIEIE_SB2_ChIso_HadronicPhoton"  ,
    # "phosel_AntiSIEIE_SB2_ChIso_HadronicFake"    ,
    #"phosel_R9"                                  ,
    # "phosel_NGenuinePhoton"                      ,
    # "phosel_NMisIDEle"                           ,
    # "phosel_NHadronicPhoton"                     ,
    # "phosel_NHadronicFake"                       ,
    # "phosel_PhotonCategory"                      ,
    # "phosel_MassLepGamma"                        ,
    "phosel_MassEGamma"                          ,
    # "phosel_MassEGamma_GenuinePhoton"            ,
    # "phosel_MassEGamma_MisIDEle"                 ,
    # "phosel_MassEGamma_HadronicPhoton"           ,
    # "phosel_MassEGamma_HadronicFake"             ,
    # "phosel_MassEGamma_NonPrompt"                ,
    #"phosel_MassCuts"                            ,
    # "phosel_noCutSIEIEChIso_GenuinePhoton"       ,
    # "phosel_noCutSIEIEChIso_MisIDEle"            ,
    # "phosel_noCutSIEIEChIso_HadronicPhoton"      ,
    # "phosel_noCutSIEIEChIso_HadronicFake"        ,
    #"phosel_noCutSIEIEChIso"                     
]


myPlotList   =[
    "presel_jet1Pt"                              ,
    "presel_Njet"                                ,
    "presel_Nbjet"                               ,
    "presel_muPt"                                ,
    "presel_muEta"                               ,
    "presel_muPhi"                               ,
    "presel_elePt"                               ,
    "presel_eleSCEta"                            ,
    "presel_elePhi"                              ,
    "presel_nVtx"                                ,
    # "phosel_nVtx"                                , # Aloke forgot to create it
    "phosel_jet1Pt"                              ,
    "phosel_Nphotons"                            ,
    "phosel_LeadingPhotonEt"                     ,
    "phosel_LeadingPhotonPhi"                    ,
    "phosel_LeadingPhotonEta"                    ,
    "phosel_elePt"                               ,
    "phosel_eleSCEta"                            ,
    "phosel_muPt"                                ,
    "phosel_muEta"                               ,
    "phosel_Njet"                                ,
    # "phosel_Nbjet"                               , # Aloke forgot to creat it
    # "phosel_PhotonCategory"                      ,
]

























