btagWeightCategory = ["1","(1-btagWeight[0])","(btagWeight[2])","(btagWeight[1])"]

def GetHistogramInfo_2Dplot(extraCuts="(passPresel_Mu && nJet>=3 && nBJet>=1)*", extraPhotonCuts="(passPresel_Mu && nJet>=3 && nBJet>=1 && %s)*", nBJets=1):
    histogramInfo = {
    "2D_PhotonEt"                         : ["phoEt[0]", "mcPt", "2D_PhotonEt",                                        [300,0,300],  [300,0,300],extraPhotonCuts%("nPho==1")       , "", True],
    "phosel_2DChIsoSIEIE"                 : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE",                [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_2DChIsoSIEIE"                 : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE",                [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso "), "", True],
    "phosel_2DChIsoSIEIE_GenuinePhoton"   : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_GenuinePhoton",  [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"), "", False],
    "phosel_2DChIsoSIEIE_MisIDEle"        : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_MisIDEle",       [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle"), "", False],
    "phosel_2DChIsoSIEIE_HadronicPhoton"  : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_HadronicPhoton", [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
    "phosel_2DChIsoSIEIE_HadronicFake"    : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_HadronicFake",   [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"), "", False],
    "phosel_2DChIsoSIEIE_GenuinePhoton"   : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_GenuinePhoton",  [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine "), "", False],
    "phosel_2DChIsoSIEIE_MisIDEle"        : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_MisIDEle",       [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle "), "", False],
    "phosel_2DChIsoSIEIE_HadronicPhoton"  : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_HadronicPhoton", [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "), "", False],
    "phosel_2DChIsoSIEIE_HadronicFake"    : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_HadronicFake",   [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake "), "", False],
    "phosel_2DChIsoHoverE"                : ["loosePhoPFChIso", "loosePhoHoverE", "phosel_2DChIsoHoverE",              [400,0,0.2],  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso "), "", True],
    "phosel_2DChIsoHoverE_Nonprompt"      : ["loosePhoPFChIso", "loosePhoHoverE", "phosel_2DChIsoHoverE_Nonprompt",    [400,0,0.2],  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso  && (loosePhotonIsHadronicFake || loosePhotonIsHadronicPhoton)"), "", False],
    "phosel_2DdRjetphoChIso"                    : ["dRPhotonJet[0]", "loosePhoPFChIso", "phosel_2DdRjetphoChIso",      [200,0,5],    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"),"", True], 
    "phosel_2DChIsoSIEIE_dRcut"                 : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_dRcut",    [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoJetDR>0.4 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso "), "", True],
    "phosel_2DChIsoSIEIE_dRcut_GenuinePhoton"   : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_dRcut_GenuinePhoton", [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoJetDR>0.4 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine "), "", False],
    "phosel_2DChIsoSIEIE_dRcut_MisIDEle"        : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_dRcut_MisIDEle",      [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoJetDR>0.4 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle "), "", False],
    "phosel_2DChIsoSIEIE_dRcut_HadronicPhoton"  : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_dRcut_HadronicPhoton",[500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoJetDR>0.4 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "), "", False],
    "phosel_2DChIsoSIEIE_dRcut_HadronicFake"    : ["loosePhoPFChIso", "loosePhoSIEIE", "phosel_2DChIsoSIEIE_dRcut_HadronicFake",  [500,0,0.05], [200,0,20], extraPhotonCuts%("loosePhoJetDR>0.4 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake "), "", False],

    }

    return histogramInfo

# extra1Cuts
def GetHistogramInfo(extraCuts="(passPresel_Mu && nJet>=3 && nBJet>=1)*", extraPhotonCuts="(passPresel_Mu && nJet>=3 && nBJet>=1 && %s)*", nBJets=1):

    histogramInfo = {  
    "presel_jet1Pt"                              : ["jetPt[0]"  , "presel_jet1Pt"   ,                       [1000,0,1000], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_fwdjet1Pt"                           : ["fwdJetPt[0]","presel_fwdjet1Pt",                       [1000,0,1000], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_jet2Pt"                              : ["jetPt[1]"  , "presel_jet2Pt"   ,                       [600,0,600],   extraPhotonCuts%("nPho==0")       , "", True],
    "presel_jet3Pt"                              : ["jetPt[2]"  , "presel_jet3Pt"   ,                       [600,0,600],   extraPhotonCuts%("nPho==0")       , "", True],
    "presel_jet4Pt"                              : ["jetPt[3]"  , "presel_jet4Pt"   ,                       [600,0,600],   extraPhotonCuts%("nPho==0")       , "", True],
    "presel_Njet"                                : ["nJet"      , "presel_Njet"     ,                       [15,0,15],     extraPhotonCuts%("nPho==0")       , "", True],
    "presel_NFwdjet"                             : ["nfwdJet"   , "presel_NFwdjet"  ,                       [15,0,15],     extraPhotonCuts%("nPho==0")       , "", True],
    "presel_Nbjet"                               : ["nBJet"     , "presel_Nbjet"    ,                       [10,0,10],     extraPhotonCuts%("nPho==0")       , "", True],
    "presel_muPt"                                : ["muPt"      , "presel_muPt"     ,                       [600,0,600],   extraPhotonCuts%("nPho==0")       , "", True],
    "presel_muEta"                               : ["muEta"     , "presel_muEta"    ,                       [100,-2.4,2.4],extraPhotonCuts%("nPho==0")       , "", True],
    "presel_muPhi"                               : ["muPhi"     , "presel_muPhi"    ,                       [100,-3.15,3.15], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_elePt"                               : ["elePt"     , "presel_elePt"    ,                       [600,0,600],      extraPhotonCuts%("nPho==0")       , "", True],
    "presel_eleSCEta"                            : ["eleSCEta"  , "presel_eleSCEta" ,                       [100,-2.4,2.4],   extraPhotonCuts%("nPho==0")       , "", True],
    "presel_elePhi"                              : ["elePhi"    , "presel_elePhi"   ,                       [100,-3.15,3.15], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_M3"                                  : ["M3"        , "presel_M3"       ,                       [550,50,600],     extraPhotonCuts%("nPho==0")       , "", True],
    "presel_MET"                                 : ["pfMET"     , "presel_MET"      ,                       [300,0,600],      extraPhotonCuts%("nPho==0")       , "", True],
    "presel_METPhi"                              : ["pfMETPhi"  , "presel_METPhi"   ,                       [100,-3.15,3.15], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_nVtx"                                : ["nVtx"      , "presel_nVtx"     ,                       [50,0,50],        extraPhotonCuts%("nPho==0")       , "", True],
    "presel_WtransMass"                          : ["WtransMass", "presel_WtransMass",                      [200,0,200], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_WtransMass_METless30"                : ["WtransMass", "presel_WtransMass_METless30",            [200,0,200], extraPhotonCuts%("pfMET<30")                         , "", True],
    "presel_WtransMass_METgreat30"               : ["WtransMass", "presel_WtransMass_METgreat30",           [200,0,200], extraPhotonCuts%("pfMET>30")                        , "", True],
    "presel_WtransMass_METless30_control"        : ["WtransMass", "presel_WtransMass_METless30_control",    [200,0,200], extraPhotonCuts%("pfMET<30 && nPho==0")      , "", True],
    "presel_WtransMass_METgreat30_control"       : ["WtransMass", "presel_WtransMass_METgreat30_control",   [200,0,200], extraPhotonCuts%("pfMET>30 && nPho==0")     , "", True],
    "presel_HT"                                  : ["HT"        , "presel_HT"        ,                      [1500,0,1500], extraPhotonCuts%("nPho==0")       , "", True],
    "presel_nVtxup"                              : ["nVtx"      , "presel_nVtxup"   ,                       [50,0,50], extraPhotonCuts%("nPho==0"), "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
    "presel_nVtxdo"                              : ["nVtx"      , "presel_nVtxdo"   ,                       [50,0,50], extraPhotonCuts%("nPho==0"), "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
    "presel_nVtxNoPU"                            : ["nVtx"      , "presel_nVtxNoPU" ,                       [50,0,50], extraPhotonCuts%("nPho==0"), "%sevtWeight*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
   
    "phosel_nVtxup"                              : ["nVtx"      , "phosel_nVtxup"   ,                       [50,0,50], extraPhotonCuts%("nPho==1"), "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
    "phosel_nVtxdo"                              : ["nVtx"      , "phosel_nVtxdo"   ,                       [50,0,50], extraPhotonCuts%("nPho==1"), "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
    "phosel_nVtxNoPU"                            : ["nVtx"      , "phosel_nVtxNoPU" ,                       [50,0,50], extraPhotonCuts%("nPho==1"), "%sevtWeight*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("nPho==0") ), False],
   
    "phosel_WtransMass_METless30"                : ["WtransMass", "phosel_WtransMass_METless30",            [200,0,200], extraPhotonCuts%("pfMET<30 && nPho==1")              , "", True],
    "phosel_WtransMass_METgreat30"               : ["WtransMass", "phosel_WtransMass_METgreat30",           [200,0,200], extraPhotonCuts%("pfMET>30 && nPho==1")             , "", True],
   
    "phosel_nVtx"                                : ["nVtx"      , "phosel_nVtx"     ,                       [50,0,50], extraPhotonCuts%("nPho==1") , "", True],
    "phosel_nVtx_GenuinePhoton"                  : ["nVtx"      , "phosel_nVtx_GenuinePhoton" ,             [50,0,50], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_nVtx_MisIDEle"                       : ["nVtx"      , "phosel_nVtx_MisIDEle" ,                  [50,0,50], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_nVtx_HadronicPhoton"                 : ["nVtx"      , "phosel_nVtx_HadronicPhoton",             [50,0,50], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_nVtx_HadronicFake"                   : ["nVtx"      , "phosel_nVtx_HadronicFake"  ,             [50,0,50], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),   "", True], 

    "phosel_jet1Pt"                              : ["jetPt[0]"  , "phosel_jet1Pt"          ,                [1000,0,1000], extraPhotonCuts%("nPho==1") ,                           "", True],
    "phosel_jet1Pt_GenuinePhoton"                : ["jetPt[0]"  , "phosel_jet1Pt_GenuinePhoton" ,           [1000,0,1000], extraPhotonCuts%("nPho==1 && photonIsGenuine") ,        "", True],
    "phosel_jet1Pt_MisIDEle"                     : ["jetPt[0]"  , "phosel_jet1Pt_MisIDEle" ,                [1000,0,1000], extraPhotonCuts%("nPho==1 && photonIsMisIDEle") ,       "", True],
    "phosel_jet1Pt_HadronicPhoton"               : ["jetPt[0]"  , "phosel_jet1Pt_HadronicPhoton" ,          [1000,0,1000], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton") , "", True],
    "phosel_jet1Pt_HadronicFake"                 : ["jetPt[0]"  , "phosel_jet1Pt_HadronicFake" ,            [1000,0,1000], extraPhotonCuts%("nPho==1 && photonIsHadronicFake") ,   "", True],

    "phosel_fwdjet1Pt"                           : ["fwdJetPt[0]","phosel_fwdjet1Pt",                       [1000,0,1000], extraPhotonCuts%("nPho==1") , "", True],
    "phosel_NFwdjet"                             : ["nfwdJet"   , "phosel_NFwdjet" ,                        [15,0,15], extraPhotonCuts%("nPho==1")     , "", True],
    "phosel_Nphotons"                            : ["nPho"      , "phosel_Nphotons",                        [3,1,4], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_Nphotons_GenuinePhoton"              : ["nPho"      , "phosel_Nphotons_GenuinePhoton",          [3,1,4], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_Nphotons_MisIDEle"                   : ["nPho"      , "phosel_Nphotons_MisIDEle",               [3,1,4], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_Nphotons_HadronicPhoton"             : ["nPho"      , "phosel_Nphotons_HadronicPhoton",         [3,1,4], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_Nphotons_HadronicFake"               : ["nPho"      , "phosel_Nphotons_HadronicFake",           [3,1,4], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_Nphotons_NonPrompt"                  : ["nPho"      , "phosel_Nphotons_NonPrompt",              [3,1,4], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    # "phosel_LeadingPhotonEt"                     : ["phoEt[0]"  , "phosel_LeadingPhotonEt" ,                [300,0,300], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_GenPhoPt"                            : ["mcPt"      , "phosel_GenPho" ,                         [300,0,300] , "(mcPID==22 && mcPt>=20 && abs(mcEta)<=1.5 && (mcStatus==1 || mcStatus==71))*","", True],
    "phosel_GenPhoEta"                           : ["abs(mcEta)", "phosel_GenEta" ,                         [15,0,1.5], "(mcPID==22 && mcPt>=20 && abs(mcEta)<=1.5 && (mcStatus==1 || mcStatus==71))*","",True],
    "phosel_LeadingPhotonEt"                     : ["phoEt[0]"  , "phosel_LeadingPhotonEt"               ,  [300,0,300], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonEt_GenuinePhoton"       : ["phoEt[0]"  , "phosel_LeadingPhotonEt_GenuinePhoton" ,  [300,0,300], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_LeadingPhotonEt_MisIDEle"            : ["phoEt[0]"  , "phosel_LeadingPhotonEt_MisIDEle" ,       [300,0,300], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_LeadingPhotonEt_HadronicPhoton"      : ["phoEt[0]"  , "phosel_LeadingPhotonEt_HadronicPhoton",  [300,0,300], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_LeadingPhotonEt_HadronicFake"        : ["phoEt[0]"  , "phosel_LeadingPhotonEt_HadronicFake"  ,  [300,0,300], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),   "", True], 
    "phosel_LeadingPhotonPhi"                    : ["phoPhi[0]" , "phosel_LeadingPhotonPhi"               , [50,-4,4], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonPhi_GenuinePhoton"      : ["phoPhi[0]" , "phosel_LeadingPhotonPhi_GenuinePhoton" , [50,-4,4], extraPhotonCuts%("nPho==1 && photonIsGenuine"),        "", True],
    "phosel_LeadingPhotonPhi_MisIDEle"           : ["phoPhi[0]" , "phosel_LeadingPhotonPhi_MisIDEle"      , [50,-4,4], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"),       "", True],
    "phosel_LeadingPhotonPhi_HadronicPhoton"     : ["phoPhi[0]" , "phosel_LeadingPhotonPhi_HadronicPhoton", [50,-4,4], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_LeadingPhotonPhi_HadronicFake"       : ["phoPhi[0]" , "phosel_LeadingPhotonPhi_HadronicFake"  , [50,-4,4], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),   "", True], 
    "phosel_LeadingPhotonEta"                    : ["phoEta[0]" , "phosel_LeadingPhotonEta"               , [50,-2.5,2.5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonEta_GenuinePhoton"      : ["phoEta[0]" , "phosel_LeadingPhotonEta_GenuinePhoton" , [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsGenuine"),        "", True],
    "phosel_LeadingPhotonEta_MisIDEle"           : ["phoEta[0]" , "phosel_LeadingPhotonEta_MisIDEle"      , [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"),       "", True],
    "phosel_LeadingPhotonEta_HadronicPhoton"     : ["phoEta[0]" , "phosel_LeadingPhotonEta_HadronicPhoton", [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_LeadingPhotonEta_HadronicFake"       : ["phoEta[0]" , "phosel_LeadingPhotonEta_HadronicFake"  , [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),   "", True], 
    "phosel_LeadingPhotonEt_Isolated"            : ["phoEt[0]"  , "phosel_LeadingPhotonEt_Isolated" ,       [300,0,300], extraPhotonCuts%("nPho==1 && (photonIsGenuine||photonIsMisIDEle)"), "", True],
    "phosel_LeadingPhotonEt_NonPrompt"           : ["phoEt[0]"  , "phosel_LeadingPhotonEt_NonPrompt",       [300,0,300], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_LeadingPhotonEta"                    : ["phoEta[0]"     , "phosel_LeadingPhotonEta"       ,     [50,-2.5,2.5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonSCEta"                  : ["phoSCEta[0]"   , "phosel_LeadingPhotonSCEta"     ,     [50,-2.5,2.5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonSCEta_GenuinePhoton"    : ["phoSCEta[0]"   , "phosel_LeadingPhotonSCEta_GenuinePhoton",             [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_LeadingPhotonSCEta_MisIDEle"         : ["phoSCEta[0]"   , "phosel_LeadingPhotonSCEta_MisIDEle",                  [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_LeadingPhotonSCEta_NonPrompt"        : ["phoSCEta[0]"   , "phosel_LeadingPhotonSCEta_NonPrompt",                 [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_LeadingPhotonabsSCEta"               : ["abs(phoSCEta[0])"   , "phosel_LeadingPhotonabsSCEta"     ,              [50,-2.5,2.5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_LeadingPhotonabsSCEta_GenuinePhoton" : ["abs(phoSCEta[0])"   , "phosel_LeadingPhotonabsSCEta_GenuinePhoton"     ,[50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_LeadingPhotonabsSCEta_MisIDEle"      : ["phoSCEta[0]"        , "phosel_LeadingPhotonabsSCEta_MisIDEle",          [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_LeadingPhotonabsSCEta_NonPrompt"     : ["abs(phoSCEta[0])"   , "phosel_LeadingPhotonabsSCEta_NonPrompt",         [50,-2.5,2.5], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_dRLeadingPhotonJet"                  : ["dRPhotonJet[0]"   , "phosel_dRLeadingPhotonJet"            ,            [500,0,5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_dRLeadingPhotonJet_GenuinePhoton"    : ["dRPhotonJet[0]"   , "phosel_dRLeadingPhotonJet_GenuinePhoton"         , [500,0,5], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_dRLeadingPhotonJet_MisIDEle"         : ["dRPhotonJet[0]"   , "phosel_dRLeadingPhotonJet_MisIDEle" ,              [500,0,5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_dRLeadingPhotonJet_NonPrompt"        : ["dRPhotonJet[0]"   , "phosel_dRLeadingPhotonJet_NonPrompt"   ,           [500,0,5], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", False],
    "phosel_dRLeadingPromptPhotonJet"            : ["dRPhotonJet[0]"   , "phosel_dRLeadingPromptPhotonJet"      ,            [200,0,5], extraPhotonCuts%("nPho==1 && (photonIsGenuine||photonIsMisIDEle)"), "", False],
    "phosel_dRLeadingPromptPhotonLepton"         : ["dRPhotonLepton[0]", "phosel_dRLeadingPromptPhotonLepton"   ,            [120,0,6], extraPhotonCuts%("nPho==1 && (photonIsGenuine||photonIsMisIDEle)"), "", False],
    "phosel_dRLeadingHadronicPhotonLepton"       : ["dRPhotonLepton[0]", "phosel_dRLeadingHadronicPhotonLepton" ,            [120,0,6], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"),"", False],
    "phosel_dRLeadingPhotonLepton_GenuinePhoton" : ["dRPhotonLepton[0]", "phosel_dRLeadingPhotonLepton_GenuinePhoton"  ,     [600,0,6], extraPhotonCuts%("nPho==1 && photonIsGenuine"),"", False],
    "phosel_dRLeadingPhotonLepton_MisIDEle"      : ["dRPhotonLepton[0]", "phosel_dRLeadingPhotonLepton_MisIDEle"       ,     [600,0,6], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"),"", False],
    "phosel_dRLeadingPhotonLepton_NonPrompt"     : ["dRPhotonLepton[0]", "phosel_dRLeadingPhotonLepton_NonPrompt",           [600,0,6], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", False],
    "phosel_dRLeadingHadronicFakeLepton"         : ["dRPhotonLepton[0]", "phosel_dRLeadingHadronicFakeLepton"   ,            [120,0,6], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),"", False],
    "phosel_dRLeadingPhotonLepton"               : ["dRPhotonLepton[0]", "phosel_dRLeadingPhotonLepton"         ,            [600,0,6], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_phoJetDR"                            : ["phoJetDR"         , "phosel_phoJetDR"                      ,            [200,0,5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_WtransMass"                          : ["WtransMass"    , "phosel_WtransMass"      ,              [200,0,200], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_WtransMass_GenuinePhoton"            : ["WtransMass"    , "phosel_WtransMass_GenuinePhoton"      ,[200,0,200], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],       
    "phosel_WtransMass_MisIDEle"                 : ["WtransMass"    , "phosel_WtransMass_MisIDEle"      ,     [200,0,200], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_WtransMass_HadronicPhoton"           : ["WtransMass"    , "phosel_WtransMass_HadronicPhoton"     ,[200,0,200], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_WtransMass_HadronicFake"             : ["WtransMass"    , "phosel_WtransMass_HadronicFake"      , [200,0,200], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_HT"                                  : ["HT"            , "phosel_HT",      [1500,0,1500], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_HT_GenuinePhoton"                    : ["HT" , "phosel_HT_GenuinePhoton" ,  [1500,0,1500], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_HT_MisIDEle"                         : ["HT" , "phosel_HT_MisIDEle" ,       [1500,0,1500], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_HT_NonPrompt"                        : ["HT" , "phosel_HT_NonPrompt" ,      [1500,0,1500], extraPhotonCuts%("nPho==1 && (photonIsHadronicFake||photonIsHadronicPhoton)"), "", True],
    "phosel_M3"                                  : ["M3" , "phosel_M3"              ,   [550,50,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_M3_GenuinePhoton"                    : ["M3" , "phosel_M3_GenuinePhoton",   [550,50,600], extraPhotonCuts%("nPho==1 && photonIsGenuine")       , "", False],
    "phosel_M3_MisIDEle"                         : ["M3" , "phosel_M3_MisIDEle"     ,   [550,50,600], extraPhotonCuts%("nPho==1 && photonIsMisIDEle")      , "", False],
    "phosel_M3_HadronicPhoton"                   : ["M3" , "phosel_M3_HadronicPhoton",  [550,50,600], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", False],
    "phosel_M3_HadronicFake"                     : ["M3" , "phosel_M3_HadronicFake" ,   [550,50,600], extraPhotonCuts%("nPho==1 && photonIsHadronicFake")  , "", False],
    "phosel_M3_NonPrompt"                        : ["M3"         , "phosel_M3_NonPrompt"  ,       [550,50,600], extraPhotonCuts%("nPho==1 && (photonIsHadronicFake||photonIsHadronicPhoton)")  , "", False],
    "phosel_M3_gamma"                            : ["M3_gamma"   , "phosel_M3_gamma"         ,    [1000,0,1000], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_Mbjj_gamma"                          : ["M_bjjgamma" , "phosel_Mbjj_gamma"         ,  [1000,0,1000], extraPhotonCuts%("nPho==1"), "", True],

    "phosel_MET"                                  : ["pfMET"      , "phosel_MET"             ,    [300,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_MET_GenuinePhoton"                    : ["pfMET"      , "phosel_MET_GenuinePhoton",   [300,0,600], extraPhotonCuts%("nPho==1 && photonIsGenuine")       , "", False],
    "phosel_MET_MisIDEle"                         : ["pfMET"      , "phosel_MET_MisIDEle"     ,   [300,0,600], extraPhotonCuts%("nPho==1 && photonIsMisIDEle")      , "", False],
    "phosel_MET_HadronicPhoton"                   : ["pfMET"      , "phosel_MET_HadronicPhoton",  [300,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", False],
    "phosel_MET_HadronicFake"                     : ["pfMET"      , "phosel_MET_HadronicFake" ,   [300,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicFake")  , "", False],

    "phosel_elePt"                               : ["elePt"         , "phosel_elePt"           ,           [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_elePt_GenuinePhoton"                 : ["elePt"         , "phosel_elePt_GenuinePhoton" ,       [600,0,600], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_elePt_MisIDEle"                      : ["elePt"         , "phosel_elePt_MisIDEle" ,            [600,0,600], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_elePt_HadronicPhoton"                : ["elePt"         , "phosel_elePt_HadronicPhoton"  ,     [600,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_elePt_HadronicFake"                  : ["elePt"         , "phosel_elePt_HadronicFake"    ,     [600,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_elePt_NonPrompt"                     : ["elePt"         , "phosel_elePt_NonPrompt" ,           [600,0,600], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_eleSCEta"                            : ["eleSCEta"      , "phosel_eleSCEta"        ,           [100,-2.4,2.4], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_eleSCEta_GenuinePhoton"              : ["eleSCEta"      , "phosel_eleSCEta_GenuinePhoton" ,    [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_eleSCEta_MisIDEle"                   : ["eleSCEta"      , "phosel_eleSCEta_MisIDEle" ,         [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_eleSCEta_HadronicPhoton"             : ["eleSCEta"      , "phosel_eleSCEta_HadronicPhoton"  ,  [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_eleSCEta_HadronicFake"               : ["eleSCEta"      , "phosel_eleSCEta_HadronicFake"    ,  [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_eleSCEta_NonPrompt"                  : ["eleSCEta"      , "phosel_eleSCEta_NonPrompt" ,        [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_muPt"                                : ["muPt"          , "phosel_muPt"  ,                     [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_muPt_GenuinePhoton"                  : ["muPt"          , "phosel_muPt_GenuinePhoton"  ,       [600,0,600], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_muPt_MisIDEle"                       : ["muPt"          , "phosel_muPt_MisIDEle"  ,            [600,0,600], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_muPt_HadronicPhoton"                 : ["muPt"          , "phosel_muPt_HadronicPhoton"   ,     [600,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],  
    "phosel_muPt_HadronicFake"                   : ["muPt"          , "phosel_muPt_HadronicFake"     ,     [600,0,600], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],  
    "phosel_muPt_NonPrompt"                      : ["muPt"          , "phosel_muPt_NonPrompt"  ,           [600,0,600], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],  
    "phosel_muEta"                               : ["muEta"         , "phosel_muEta"           ,           [100,-2.4,2.4], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_muEta_GenuinePhoton"                 : ["muEta"         , "phosel_muEta_GenuinePhoton" ,       [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_muEta_MisIDEle"                      : ["muEta"         , "phosel_muEta_MisIDEle" ,            [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_muEta_HadronicPhoton"                : ["muEta"         , "phosel_muEta_HadronicPhoton"  ,     [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_muEta_HadronicFake"                  : ["muEta"         , "phosel_muEta_HadronicFake"    ,     [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_muEta_NonPrompt"                     : ["muEta"         , "phosel_muEta_NonPrompt" ,           [100,-2.4,2.4], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],

    "phosel_Njet"                                : ["nJet"          , "phosel_Njet"            ,         [15,0,15], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_Njet_GenuinePhoton"                  : ["nJet"          , "phosel_Njet_GenuinePhoton" ,      [15,0,15], extraPhotonCuts%("nPho==1 && photonIsGenuine")        , "", True],
    "phosel_Njet_MisIDEle"                       : ["nJet"          , "phosel_Njet_MisIDEle" ,           [15,0,15], extraPhotonCuts%("nPho==1 && photonIsMisIDEle")       , "", True],
    "phosel_Njet_HadronicPhoton"                 : ["nJet"          , "phosel_Njet_HadronicPhoton"     , [15,0,15], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton") , "", True], 
    "phosel_Njet_HadronicFake"                   : ["nJet"          , "phosel_Njet_HadronicFake"     ,   [15,0,15], extraPhotonCuts%("nPho==1 && photonIsHadronicFake")   , "", True],
    "phosel_Njet_NonPrompt"                      : ["nJet"          , "phosel_Njet_NonPrompt" ,          [15,0,15], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_NfwdJet"                             : ["nfwdJet"       , "phosel_Nfwdjet"            ,     [15,0,15], extraPhotonCuts%("nPho==1"), "", True],
    
    "phosel_Nbjet"                               : ["nBJet"         , "phosel_Nbjet"           ,        [10,0,10], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_Nbjet_GenuinePhoton"                 : ["nBJet"         , "phosel_Nbjet_GenuinePhoton"   ,  [10,0,10], extraPhotonCuts%("nPho==1 && photonIsGenuine")        , "", True],
    "phosel_Nbjet_MisIDEle"                      : ["nBJet"         , "phosel_Nbjet_MisIDEle"        ,  [10,0,10], extraPhotonCuts%("nPho==1 && photonIsMisIDEle")       , "", True],
    "phosel_Nbjet_HadronicPhoton"                : ["nBJet"         , "phosel_Nbjet_HadronicPhoton"  ,  [10,0,10], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton") , "", True],
    "phosel_Nbjet_HadronicFake"                  : ["nBJet"         , "phosel_Nbjet_HadronicFake"    ,  [10,0,10], extraPhotonCuts%("nPho==1 && photonIsHadronicFake")   , "", True],
    
    "phosel_HoverE"                              : ["phoHoverE"     , "phosel_HoverE"          ,        [100,0.,.04], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_noCut_HoverE"                        : ["loosePhoHoverE"  , "phosel_noCut_HoverE" ,         [100,0.,.2], extraPhotonCuts%("loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso "), "", True],
    "phosel_SIEIE"                               : ["phoSIEIE"      , "phosel_SIEIE"  ,                 [100,0.,.07], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_SIEIE_GenuinePhoton"                 : ["phoSIEIE"      , "phosel_SIEIE_GenuinePhoton"  ,   [100,0.,.07], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_SIEIE_MisIDEle"                      : ["phoSIEIE"      , "phosel_SIEIE_MisIDEle"  ,        [100,0.,.07], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_SIEIE_HadronicPhoton"                : ["phoSIEIE"      , "phosel_SIEIE_HadronicPhoton"   , [100,0.,.07], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_SIEIE_HadronicFake"                  : ["phoSIEIE"      , "phosel_SIEIE_HadronicFake"     , [100,0.,.07], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"), "", True],
    "phosel_SIEIE_NonPrompt"                     : ["phoSIEIE"      , "phosel_SIEIE_NonPrompt"  ,       [100,0.,.07], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_ChIso"                               : ["phoPFChIso"    , "phosel_ChIso"  ,                 [100,0,.5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_ChIso_GenuinePhoton"                 : ["phoPFChIso"    , "phosel_ChIso_GenuinePhoton",     [100,0,.5], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_ChIso_MisIDEle"                      : ["phoPFChIso"    , "phosel_ChIso_MisIDEle",          [100,0,.5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_ChIso_NonPrompt"                     : ["phoPFChIso"    , "phosel_ChIso_NonPrompt",         [100,0,.5], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_NeuIso"                              : ["phoPFNeuIso"   , "phosel_NeuIso"          ,        [100,0,5.], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_NeuIso_GenuinePhoton"                : ["phoPFNeuIso"   , "phosel_NeuIso_GenuinePhoton",    [100,0,5.], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_NeuIso_MisIDEle"                     : ["phoPFNeuIso"   , "phosel_NeuIso_MisIDEle",         [100,0,5.], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_NeuIso_NonPrompt"                    : ["phoPFNeuIso"   , "phosel_NeuIso_NonPrompt",        [100,0,5.], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],   
    "phosel_PhoIso"                              : ["phoPFPhoIso"   , "phosel_PhoIso"          ,        [50,0,5], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_PhoIso_GenuinePhoton"                : ["phoPFPhoIso"   , "phosel_PhoIso_GenuinePhoton",    [100,0,5], extraPhotonCuts%("nPho==1 && photonIsGenuine"), "", True],
    "phosel_PhoIso_MisIDEle"                     : ["phoPFPhoIso"   , "phosel_PhoIso_MisIDEle",         [100,0,5], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"), "", True],
    "phosel_PhoIso_NonPrompt"                    : ["phoPFPhoIso"   , "phosel_PhoIso_NonPrompt",        [100,0,5], extraPhotonCuts%("nPho==1 && (photonIsHadronicPhoton||photonIsHadronicFake)"), "", True],
    "phosel_noCut_SIEIE_noChIso"                 : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso" ,  [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso "),"", True],
    "phosel_noCut_SIEIE_noChIso_GenuinePhoton"   : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso_GenuinePhoton" ,[700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine "),"", True],   
    "phosel_noCut_SIEIE_noChIso_MisIDEle"        : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso_MisIDEle" ,     [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle "),"", True],
    "phosel_noCut_SIEIE_noChIso_HadronicPhoton"  : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso_HadronicPhoton",[700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "),"", True],
    "phosel_noCut_SIEIE_noChIso_HadronicFake"    : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso_HadronicFake"  ,[700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake "),"", True],
    "phosel_noCut_SIEIE_noChIso_NonPrompt"       : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_noChIso_NonPrompt" ,    [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (loosePhotonIsHadronicFake||loosePhotonIsHadronicPhoton) "),"", True],
    "phosel_noCut_SIEIE"                         : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE"                ,       [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_SIEIE_GenuinePhoton"           : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_GenuinePhoton"  ,       [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"), "", True],
    "phosel_noCut_SIEIE_MisIDEle"                : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_MisIDEle"       ,       [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle"), "", True],
    "phosel_noCut_SIEIE_HadronicPhoton"          : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_HadronicPhoton" ,       [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", True],
    "phosel_noCut_SIEIE_HadronicFake"            : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_HadronicFake"   ,       [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"), "", True],
    "phosel_noCut_SIEIE_NonPrompt"               : ["loosePhoSIEIE"   , "phosel_noCut_SIEIE_NonPrompt",             [700,0.,.07], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso  && (loosePhotonIsHadronicFake||loosePhotonIsHadronicPhoton)"),"", True],
    "phosel_mediumID_ChIso"                      : ["loosePhoPFChIso" , "phosel_mediumID_ChIso"                ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_mediumID_ChIso_GenuinePhoton"        : ["loosePhoPFChIso" , "phosel_mediumID_ChIso_GenuinePhoton"  ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"),        "", False],
    "phosel_mediumID_ChIso_MisIDEle"             : ["loosePhoPFChIso" , "phosel_mediumID_ChIso_MisIDEle"       ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle"),       "", False],
    "phosel_mediumID_ChIso_HadronicPhoton"       : ["loosePhoPFChIso" , "phosel_mediumID_ChIso_HadronicPhoton" ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
    "phosel_mediumID_ChIso_HadronicFake"         : ["loosePhoPFChIso" , "phosel_mediumID_ChIso_HadronicFake"   ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"),   "", False],
    "phosel_noCut_ChIso"                         : ["loosePhoPFChIso" , "phosel_noCut_ChIso"         ,              [200,0,20], extraPhotonCuts%("loosePhoIsBarrel && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_ChIso_PUdown"                  : ["loosePhoPFChIso" , "phosel_noCut_ChIso_PUdown"         ,       [200,0,20], "", "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")), False],
    "phosel_noCut_ChIso_PUup"                    : ["loosePhoPFChIso" , "phosel_noCut_ChIso_PUup"           ,       [200,0,20], "", "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")), False],
    "phosel_noCut_ChIso_0nVtx15"                 : ["loosePhoPFChIso" , "phosel_noCut_ChIso_0nVtx15"        ,       [200,0,20], extraPhotonCuts%("nVtx<=15 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_ChIso_15nVtx20"                : ["loosePhoPFChIso" , "phosel_noCut_ChIso_15nVtx20"        ,      [200,0,20], extraPhotonCuts%("15<nVtx && nVtx<=20 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_ChIso_20nVtx25"                : ["loosePhoPFChIso" , "phosel_noCut_ChIso_20nVtx25"        ,      [200,0,20], extraPhotonCuts%("20<nVtx && nVtx<=25 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_ChIso_25nVtx50"                : ["loosePhoPFChIso" , "phosel_noCut_ChIso_25nVtx50"        ,      [200,0,20], extraPhotonCuts%("25<nVtx && nVtx<=50 && loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    "phosel_noCut_ChIso_Nonprompt_PUdown"        : ["loosePhoPFChIso" , "phosel_noCut_ChIso_Nonprompt_PUdown",      [200,0,20], "", "%sevtWeight*PUweight_Do*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso  && (loosePhotonIsHadronicFake || loosePhotonIsHadronicPhoton)")), False],
    "phosel_noCut_ChIso_Nonprompt_PUup"          : ["loosePhoPFChIso" , "phosel_noCut_ChIso_Nonprompt_PUup",        [200,0,20], "", "%sevtWeight*PUweight_Up*muEffWeight*eleEffWeight*btagWeight_1a"%(extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso  && (loosePhotonIsHadronicFake || loosePhotonIsHadronicPhoton)")), False],
    "phosel_noCut_ChIso_GenuinePhoton"           : ["loosePhoPFChIso" , "phosel_noCut_ChIso_GenuinePhoton"  ,       [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine"), "", False],
    "phosel_noCut_ChIso_MisIDEle"                : ["loosePhoPFChIso" , "phosel_noCut_ChIso_MisIDEle"       ,       [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle "), "", False],
    "phosel_noCut_ChIso_HadronicPhoton"          : ["loosePhoPFChIso" , "phosel_noCut_ChIso_HadronicPhoton" ,       [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton"), "", False],
    "phosel_noCut_ChIso_HadronicFake"            : ["loosePhoPFChIso" , "phosel_noCut_ChIso_HadronicFake"   ,       [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake"), "", False],
    # "phosel_noCut_ChIso_NonPromptPhoton"         : ["loosePhoPFChIso" , "phosel_noCut_ChIso_NonPromptPhoton",       [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && (loosePhotonIsHadronicPhoton||loosePhotonIsHadronicFake)"), "", False],
    "phosel_noCut_NeuIso"                        : ["loosePhoPFNeuIso", "phosel_noCut_NeuIso"               ,       [400,0,40], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassPhoIso")                                 , "", True],
    #"phosel_noCut_PhoIso"                        : ["loosePhoPFPhoIso", "phosel_noCut_PhoIso" ,                     [400,0,40], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso")                                 , "", True],
    "phosel_noCut_NeuIso"                        : ["loosePhoPFNeuIso", "phosel_noCut_NeuIso" ,                     [400,0,40], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassPhoIso ")                                 , "", True],
    #"phosel_noCut_PhoIso"                        : ["loosePhoPFPhoIso", "phosel_noCut_PhoIso",                      [400,0,40], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassSIEIE && loosePhoMediumIDPassChIso && loosePhoMediumIDPassNeuIso ")  , "", True],
    "phosel_AntiSIEIE_ChIso"                     : ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso"    ,               [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.02)  && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")  , "", True],
    "phosel_AntiSIEIE_ChIso_GenuinePhoton"       : ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_GenuinePhoton"  ,   [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine")       , "", False],
    "phosel_AntiSIEIE_ChIso_MisIDEle"            : ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_MisIDEle"  ,        [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle")       , "", False],
    "phosel_AntiSIEIE_ChIso_HadronicPhoton"      : ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_HadronicPhoton"  ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton")       , "", False],
    "phosel_AntiSIEIE_ChIso_HadronicFake"        : ["loosePhoPFChIso" , "phosel_AntiSIEIE_ChIso_HadronicFake"  ,    [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake")       , "", False],
    "phosel_AntiSIEIE_SB1_ChIso"                 : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB1_ChIso"    ,           [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.015)  && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")  , "", True],
    "phosel_AntiSIEIE_SB1_ChIso_GenuinePhoton"   : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB1_ChIso_GenuinePhoton"  ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.015) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine ")       , "", False],
    "phosel_AntiSIEIE_SB1_ChIso_MisIDEle"        : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB1_ChIso_MisIDEle"       ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.015) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle ")      , "", False],
    "phosel_AntiSIEIE_SB1_ChIso_HadronicPhoton"  : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB1_ChIso_HadronicPhoton" ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.015) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "), "", False],
    "phosel_AntiSIEIE_SB1_ChIso_HadronicFake"    : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB1_ChIso_HadronicFake"   ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.011 && loosePhoSIEIE<0.015) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake ")  , "", False],
    "phosel_AntiSIEIE_SB2_ChIso"                 : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB2_ChIso"    ,              [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.015 && loosePhoSIEIE<0.02)  && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso")  , "", True],
    "phosel_AntiSIEIE_SB2_ChIso_GenuinePhoton"   : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB2_ChIso_GenuinePhoton"  ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.015 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine ")       , "", False],
    "phosel_AntiSIEIE_SB2_ChIso_MisIDEle"        : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB2_ChIso_MisIDEle"       ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.015 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle ")      , "", False],
    "phosel_AntiSIEIE_SB2_ChIso_HadronicPhoton"  : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB2_ChIso_HadronicPhoton" ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.015 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "), "", False],
    "phosel_AntiSIEIE_SB2_ChIso_HadronicFake"    : ["loosePhoPFChIso" , "phosel_AntiSIEIE_SB2_ChIso_HadronicFake"   ,  [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && (loosePhoSIEIE>0.015 && loosePhoSIEIE<0.02) && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake ")  , "", False],
    "phosel_R9"                                  : ["phoR9"             , "phosel_R9",                    [100,0.3,1.2], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_NGenuinePhoton"                      : ["nPho"              , "phosel_NGenuinePhoton"    ,    [2,0,2], extraPhotonCuts%("photonIsGenuine")                       , "", False],
    "phosel_NMisIDEle"                           : ["nPho"              , "phosel_NMisIDEle"         ,    [2,0,2], extraPhotonCuts%("photonIsMisIDEle")                      , "", False],
    "phosel_NHadronicPhoton"                     : ["nPho"              , "phosel_NHadronicPhoton"   ,    [2,0,2], extraPhotonCuts%("photonIsHadronicPhoton")                , "", False],
    "phosel_NHadronicFake"                       : ["nPho"              , "phosel_NHadronicFake"     ,    [2,0,2], extraPhotonCuts%("photonIsHadronicFake")                  , "", False],
    "phosel_mcMomPIDGenuinePhoton"               : ["photonParentPID"   , "phosel_mcMomPIDGenuinePhoton", [2000,-1000,1000], extraPhotonCuts%("nPho==1 && photonIsGenuine")        , "", False],
    "phosel_mcMomPIDMisIDEle"                    : ["photonParentPID"   , "phosel_mcMomPIDMisIDEle"  ,    [2000,-1000,1000], extraPhotonCuts%("nPho==1 && photonIsMisIDEle")       , "", False],
    "phosel_mcMomPIDHadronicPhoton"              : ["photonParentPID"   , "phosel_mcMomPIDHadronicPhoton",[2000,-1000,1000], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton") , "", False],
    "phosel_mcMomPIDHadronicFake"                : ["photonParentPID"   , "phosel_mcMomPIDHadronicFake",  [2000,-1000,1000], extraPhotonCuts%("nPho==1 && photonIsHadronicFake")   , "", False],
    "phosel_PhotonCategory"                      : ["photonIsGenuine[0] + 2*photonIsMisIDEle[0] + 3*photonIsHadronicPhoton[0] + 4*photonIsHadronicFake[0]", "phosel_PhotonCategory", [4,1,5], extraPhotonCuts%("nPho==1"), "", False],
    "phosel_MassLepGamma"                        : ["phoMassLepGamma"  , "phosel_MassLepGamma",         [300,0,300], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_MassLepGammaFromW"                   : ["phoMassLepGamma"  , "phosel_MassLepGammaFromW",    [300,0,300], extraPhotonCuts%("nPho==1 && phoEt>40 && (phoGenMatchInd>0 && abs(mcMomPID[phoGenMatchInd])==24 )"), "", True],
    "phosel_MassLepGammaNotFromW"                : ["phoMassLepGamma"  , "phosel_MassLepGammaNotFromW", [300,0,300], extraPhotonCuts%("nPho==1 && phoEt>40 && !(phoGenMatchInd>0 && abs(mcMomPID[phoGenMatchInd])==24 )"), "", True],
    "phosel_MassEGamma"                          : ["phoMassLepGamma", "phosel_MassEGamma",                     [200,0,200], extraPhotonCuts%("nPho==1"),                           "", True],
    "phosel_MassEGamma_GenuinePhoton"            : ["phoMassLepGamma", "phosel_MassEGamma_GenuinePhoton",       [200,0,200], extraPhotonCuts%("nPho==1 && photonIsGenuine"),        "", True],
    "phosel_MassEGamma_MisIDEle"                 : ["phoMassLepGamma", "phosel_MassEGamma_MisIDEle",            [200,0,200], extraPhotonCuts%("nPho==1 && photonIsMisIDEle"),       "", True],
    "phosel_MassEGamma_HadronicPhoton"           : ["phoMassLepGamma", "phosel_MassEGamma_HadronicPhoton",      [200,0,200], extraPhotonCuts%("nPho==1 && photonIsHadronicPhoton"), "", True],
    "phosel_MassEGamma_HadronicFake"             : ["phoMassLepGamma", "phosel_MassEGamma_HadronicFake",        [200,0,200], extraPhotonCuts%("nPho==1 && photonIsHadronicFake"),   "", True],
    "phosel_MassEGamma_NonPrompt"                : ["phoMassLepGamma", "phosel_MassEGamma_NonPrompt",    [200,0,200], extraPhotonCuts%("nPho==1 && (photonIsHadronicFake||photonIsHadronicPhoton)"), "", True],
    "phosel_Mt_blgammaMET"                       : ["Mt_blgammaMET"  , "phosel_Mt_blgammaMET" , [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_Mt_lgammaMET"                        : ["Mt_lgammaMET"   , "phosel_Mt_lgammaMET"  , [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_M_bjj"                               : ["M_bjj"          , "phosel_M_bjj"         , [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_M_jj"                                : ["M_jj"           , "phosel_M_jj"          , [600,0,600], extraPhotonCuts%("nPho==1"), "", True],
    "phosel_MassCuts"                            : ["MassCuts"       , "phosel_MassCuts"      , [2,0,2]    , extraPhotonCuts%("nPho==1"), "", True],                  
    "presel_DilepMass"                           : ["DilepMass"      , "presel_DilepMass"     , [300,0,300], extraPhotonCuts%("nPho==0") ,"",True],
    "presel_DilepDR"                             : ["DilepDelR"      , "presel_DilepDR"       , [100,0,6]  , extraPhotonCuts%("nPho==0") ,"",True],
    "phosel_DilepMass"                           : ["DilepMass"      , "phosel_DilepMass"     , [300,0,300], extraPhotonCuts%("nPho==1"),"",True],
    #"phosel_DilepDR"                            : ["DilepDelR"      , "phosel_DilepDR"       , [100,0,6]  , extraPhotonCuts%("nPho==1"),"",True],
    "phosel_noCutSIEIEChIso_GenuinePhoton"       : ["loosePhoPFChIso" , "phosel_noCutSIEIEChIso_GenuinePhoton" , [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsGenuine "), "", False],
    "phosel_noCutSIEIEChIso_MisIDEle"            : ["loosePhoPFChIso" , "phosel_noCutSIEIEChIso_MisIDEle"      , [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsMisIDEle "), "", False],
    "phosel_noCutSIEIEChIso_HadronicPhoton"      : ["loosePhoPFChIso" , "phosel_noCutSIEIEChIso_HadronicPhoton", [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicPhoton "), "", False],
    "phosel_noCutSIEIEChIso_HadronicFake"        : ["loosePhoPFChIso" , "phosel_noCutSIEIEChIso_HadronicFake"  , [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso && loosePhotonIsHadronicFake "), "", False],
    "phosel_noCutSIEIEChIso"                     : ["loosePhoPFChIso" , "phosel_noCutSIEIEChIso"               , [200,0,20], extraPhotonCuts%("loosePhoMediumIDPassHoverE && loosePhoMediumIDPassNeuIso && loosePhoMediumIDPassPhoIso"), "", True],
    # "phosel_MassEGamma_LightTag"  : ["phoMassLepGamma", "phosel_MassEGamma_LightTag",        [200,0,200], extraPhotonCuts%("nPho==1 && Max$(jetHadronFlavour)==0"),   "", True],
    # "phosel_MassEGamma_CTag"      : ["phoMassLepGamma", "phosel_MassEGamma_CTag",            [200,0,200], extraPhotonCuts%("nPho==1 && Max$(jetHadronFlavour)==4"),   "", True],
    # "phosel_MassEGamma_BTag"      : ["phoMassLepGamma", "phosel_MassEGamma_BTag",            [200,0,200], extraPhotonCuts%("nPho==1 && Max$(jetHadronFlavour)==5"),   "", True],
    }
    return histogramInfo

   
