eosmkdir='eos root://cmseos.fnal.gov mkdir'


$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_BTagSF_l_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/ele/hists_JER_down_verytight/

$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_BTagSF_l_down_verytight/ 

$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/ele/hists_JER_down_verytight/

$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_BTagSF_l_down_verytight/ 

$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/ele/hists_JER_down_verytight/


$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_BTagSF_l_down_verytight/ 

$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2016/mu/hists_JER_down_verytight/


$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_BTagSF_l_down_verytight/ 

$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2017/mu/hists_JER_down_verytight/


$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PU_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Q2_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_Pdf_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_MuEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_EleEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_PhoEff_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_b_down_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_up_verytight/ 
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_BTagSF_l_down_verytight/ 

$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_JECTotal_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_JECTotal_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_isr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_fsr_down_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_JER_up_verytight/
$eosmkdir -p /store/user/npoudyal/histograms_2018/mu/hists_JER_down_verytight/